# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Lynn Le
# email: lelynn(at)gmail(dot)com
description: L. Le Academic Profile and Blog # this means to ignore newlines until "url:"

footer_text:
url:  # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: lelynn # your GitHub user name
twitter_username: # your Twitter handle
linkedin_username: # your LinkedIn user name
scholar_userid: # your Google Scholar ID
orcid_id: # your ORCID ID
contact_note: >
  l.le 🐒 donders(dot)ru(dot)nl
google_analytics: UA-125247478-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: 
blog_description: My blogs

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: Lynn # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    # - jekyll/scholar
    - jekyll-redirect-from
    - jemoji

# -----------------------------------------------------------------------------
# Staticman
# -----------------------------------------------------------------------------
# movieFormUrl: https://git.heroku.com/static-lynn.git
staticman:
 allowedFields: ['name', 'subject', 'comment']
 branch: gh-pages
 commitMessage: "Hey human, here is a new entry."
 filename: "entry{@timestamp}"
 format: yml
 moderation: true
 path: "_data/reviews"
 requiredFields: ['name', 'subject', 'comment']

# Jekyll-Scholar
# scholar:

#   last_name: Le

#   style: apa
#   locale: en

#   sort_by: year
#   order: descending

#   source: /_bibliography/
#   bibliography: papers.bib
#   bibliography_template: bib

#   replace_strings: true
#   join_strings: true

#   details_dir: bibliography
#   details_layout: bibtex.html
#   details_link: Details

#   query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
# jquery_version: "1.12.4"
# katex_version: "0.9.0"
# anchorjs_version: "3.2.2"

# theme: jekyll-theme-cayman
